#!/usr/bin/env php
<?php

/**
  * Import all classes used in this framework.
  * Don't worry, this has been done automatically by composer.
  *
  * Now, just run this application.
  */

require_once __DIR__ . '/vendor/autoload.php';

/**
  * OK, now call the console function statically in the kernel.
  * Wait a minute, this console function requires a kernel app as an application connector.
  * After that, just need to run it.
  *
  * This is very simple.
  */

exit(\Core\Kernel\Kernel::cli(
    new \App\Kernel()
)->run());
